//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsMenuManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsMenuManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWebsite.Resx.RsMenuManager", typeof(RsMenuManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new menu.
        /// </summary>
        public static string AddNewMenu {
            get {
                return ResourceManager.GetString("AddNewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Menu.
        /// </summary>
        public static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Item Per Column.
        /// </summary>
        public static string MaxPerColumn {
            get {
                return ResourceManager.GetString("MaxPerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Information.
        /// </summary>
        public static string MenuInformation {
            get {
                return ResourceManager.GetString("MenuInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string MenuLink {
            get {
                return ResourceManager.GetString("MenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name.
        /// </summary>
        public static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name (Vietnamese).
        /// </summary>
        public static string MenuText_VI {
            get {
                return ResourceManager.GetString("MenuText_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Manager.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Menu.
        /// </summary>
        public static string ParentMenu {
            get {
                return ResourceManager.GetString("ParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Menu.
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some errors here. Please try again!.
        /// </summary>
        public static string SaveMenu_Error {
            get {
                return ResourceManager.GetString("SaveMenu_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The menu has been saved..
        /// </summary>
        public static string SaveMenu_Success {
            get {
                return ResourceManager.GetString("SaveMenu_Success", resourceCulture);
            }
        }
    }
}
